### ISSUE TITLE
Add documentation on how to run a build without github pages

### ISSUE THREAD

**Issue by gaffo** [foambubble/foam-template#3]
You can't use pages on private repos without a paid account. Knowing the basics of doing a jekyll build would let people do either a local git hook or use somthing like aws amplify.

**Comment by jevakallio** [comment]
Yes! I'd be interested in having this added to Recipes
https://foambubble.github.io/foam/recipes

There's a To-do already. If you submit a MD document on above to foambubbles/foam, I'd love to have it!

**Comment by gaffo** [comment]
I think I don't have enough information about what is supposed to be going on to even piece this together unfortunately. 

Should the foam vscode plugin do the build / rendering to the index file?

**Comment by jevakallio** [comment]
Ideally, there should be no build step built into the Foam pipeline. As much as possible, folks should just be able to push markdown up to a git repository and a website should magically appear.

Currently this happens due to the magic of GH pages. To do this outside of GH pages, it should probably use some type of continuous integration service, or a web host that can use a git repository as its SCM and build trigger even source.

If deployment should be done from user's local machine, the step should be optional and manual. If you want to automate it, it could be then executed as a git hook.

As per Foam principles, using Foam should not require a user to know how to code. If you prefer a code solution yourself, you're welcome to do so under the other Foam principle: it's not a package deal.

https://foambubble.github.io/foam/recipes

I appreciate there's not enough context to contribute a full solution, but if you end up with a Jekyll solution or similar, I'd love to hear how you did it to learn how others might too

**Comment by juanfrank77** [comment]
I don't think Jekyll would be necessary. Since the idea is to be able to publish the "bubbles" without having to build before the sharing part. People could use Vercel to push to the git repo and then the website would be published. 
Or using another tool like zero-md, the markdown can be converted into HTML and then be hosted in any service like Surge, Netlify, etc. 

I'm saying that because my first foam workspace is actually a private repo so I encounter that situation (although I haven't published anything or want to yet). But if you want to I can do a test with that and write a recipe of other folks that might want to go that route just lmk.

**Comment by jevakallio** [comment]
@juanfrank77 that would be amazing! I'd love to have a recipe for it, too!

If the MD generation doesn't work as expected, read https://foambubble.github.io/foam/wiki-links#markdown-compatibility

**Comment by zomars** [comment]
I have a working eleventy template that can be uploaded to gitlab and generate and deploy a private site (without needing Netlify). Let me know if you're interested in contributing this

**Comment by IvoLeist** [comment]
@zomars hey I am not part of the foam team but I would be really interested in it since I sometimes need to share parts of my foam bubbles with the rest of the team. However, some of them do not use vscode. Thus, sending them individual markdown files is not very ideal...

**Comment by riccardoferretti** [comment]
I believe the following covers various use cases, including the local development for github pages: https://foambubble.github.io/foam/recipes/recipes#publish
